services:
  - type: web
    name: equiflow
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && g++ -O3 -shared -fPIC -std=c++17 -o core/libengine.so core/engine.cpp"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
